apiVersion: apps/v1
kind: Deployment
metadata:
  name: msvc-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msvc-gateway
  template:
    metadata:
      labels:
        app: msvc-gateway
    spec:
      containers:
        - name: msvc-gateway
          image: <ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/smartlogix/msvc-gateway:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"
            - name: CONFIG_SERVER_URL
              value: "http://msvc-config:8888"
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 10