apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
data:
  init.sql: |
    CREATE DATABASE authdb;
    CREATE DATABASE pedidodb;
    CREATE DATABASE inventariodb;
    CREATE DATABASE enviodb;
