server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass http://msvc-gateway:8080;
        # Nombre DNS del Service de Kubernetes (ClusterIP) — solo resuelve
        # DENTRO del cluster EKS. Este es el contenido EXACTO que vimos
        # dentro de frontend-configmap.yaml (clave "default.conf")
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

        # ← AGREGAR ESTO
    location /swagger/ {
        proxy_pass http://msvc-gateway:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }


    location / {
        try_files $uri $uri/ /index.html;
    }
}