server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass http://10.0.137.254:8080;
        # IP PRIVADA fija de una instancia EC2 — corresponde al despliegue de
        # deploy-backend.yml (docker-compose en una sola VM), donde msvc-gateway
        # corre como contenedor en esa misma red, con esa IP interna
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}