spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/pedidodb
    username: postgres
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

eureka:
  client:
    service-url:
      defaultZone: http://msvc-eureka:8761/eureka

msvc-inventario:
  url: http://msvc-inventario:8083

app:
  cors:
    allowed-origins: "*"