spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/inventariodb
    username: postgres
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

eureka:
  client:
    service-url:
      defaultZone: http://msvc-eureka:8761/eureka

app:
  cors:
    allowed-origins: "*"